### ISSUE TITLE
Binaries compiled as Debug. Not worked without VS2019.

### ISSUE THREAD

**Issue by lugovskovp** [morcibacsi/VanAnalyzer#1]
As Debug, .dll needed of Microsoft VC140 DebugCRT, so there are no possibility to start without installed Visual Studio 2019.
And nope, VS2017 can`t resolve problem, I tryed.
https://github.com/lugovskovp/VanAnalyzer/tree/master/Binaries - new worked Release bin`s.

**Comment by morcibacsi** [comment]
Thanks for the info. I checked your commits but I can't find what you changed in the source to produce the proper dll-s. If you commit those as well then I can include those changes in my repository as well.

**Comment by lugovskovp** [comment]
I didn`t edit Your code, it works properly.
I just needed VANbus protocol analizer DLL.
And when try to use it from morcibacsi/VanAnalyzer/Binaries, Iv got error: cant loadLibrary (and there are not library name).
Then I explore VANAnalyzer.dll and find - it trying to use concrt140d.dll, msvcp140d.dll, vccorlib140d.dll, vcruntime140d.dll, "*D" means - Microsoft.VC140.DebugCRT.
I.e. dll was compiled as Debug, but MS decline to contribute Debug redistrs. No way to install it.
I download VS2017comunity, but result of compile aniway dont loaded with error.
I download VS2019community ))))) and ide builded worked version.
Oufff.
So, I`d made issue in Your repository for information. But I was not sure, that You continue support it. So in issue I write my fork adress for peoples, who needed only woked dll has possibility to download it.
.
I think, best way not include my commit, but build dll as Release and renew own.
.
Thank for Your lightning answer ))

**Comment by morcibacsi** [comment]
Got it now. Going to release a proper version soon. Thanks for the heads up. By the way I am interested in every project regarding to VAN bus, so if you feel like talking about yours, or share some ideas drop me a mail at pinterpeti at gmail.com

**Comment by morcibacsi** [comment]
I included your dlls as a release. Thanks for the contribution.
