### ISSUE TITLE
Update analyzer to automatically build binaries using github actions

### ISSUE THREAD

**Issue by nbanerje** [morcibacsi/VanAnalyzer#2]
Hi! I'm a Product Manager at Saleae and we’ve made improvements to our analyzer build process. Specifically, we cleaned up the build system, and switched to cmake, so there aren't multiple project files anymore. By implementing the changes outlined [here](https://github.com/saleae/SampleAnalyzer/#updating-an-existing-analyzer-to-use-cmake--github-actions) you will be able to provide the community automatic builds in addition to a simplified build system. Let us know if you think you can make the changes or if you’d like us to make the changes for you. 

Additionally, if you would like to update your analyzer so that results appear in Logic 2’s data table you can follow the steps outlined [here](https://support.saleae.com/saleae-api-and-sdk/protocol-analyzer-sdk/framev2-hla-support-analyzer-sdk). Note that if you upgrade your analyzer to FrameV2 it will not be backward compatible with Logic 1.

We really appreciate your time and effort! Please let us know if you have any feedback or questions. Thanks!

**Comment by morcibacsi** [comment]
Thanks for reaching out! I'll look into the necessary changes and try to implement them.

**Comment by morcibacsi** [comment]
cmake build resolved in: 2439b32be6be1aaa1766eaf1c84719317d664329
FrameV2 resolved in: 5348cba9d3ec29ec6711c09009065af212d0242d

**Comment by nbanerje** [comment]
Great I tested it on my Mac and it worked. Thanks for updating it! I did realize I needed to do this: https://github.com/saleae/SampleAnalyzer/#using-downloaded-analyzer-binaries-on-macos
